--- 
cwd: /poke/data/www/orange/spotthebull/dev.stb2.orange.pokelondon.com/rails
environment: extdev
user: mongrel
group: dev
address: 127.0.0.1
port: "11000"
servers: 4
pid_file: log/mongrel.pid
log_file: log/mongrel.log
